[features]
seeds = false
skip-lint = false
[programs.localnet]
account_delegation = "6gJXtZUfzB7tiu7i1PA1tJDJgWSyamuLgdBaSs8QFhNK"
dummy_program = "6Xf5XGsg8trkvZnNenGpusQJudfTPY77Girr6TVDkqMs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/anish/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
